'use strict';

export const CHANGE_QUOTE = 'CHANGE_QUOTE';
export const UPDATE_STATUS = 'UPDATE_STATUS';
export const SAVE_NEW_GOOD_HABIT = 'SAVE_NEW_GOOD_HABIT';
export const SAVE_NEW_BAD_HABIT = 'SAVE_NEW_BAD_HABIT';
export const COMPLETE_DAILY_GOOD_HABIT = 'COMPLETE_DAILY_GOOD_HABIT';
export const COMPLETE_DAILY_BAD_HABIT = 'COMPLETE_DAILY_BAD_HABIT';
export const FIRST_LOGIN_STATUS_UPDATE = 'FIRST_LOGIN_STATUS_UPDATE';
