'use strict';

export const CHANGE_QUOTE = 'CHANGE_QUOTE';
export const UPDATE_STATUS = 'UPDATE_STATUS';
export const SAVE_NEW_GOOD_HABIT = 'SAVE_NEW_GOOD_HABIT';
export const SAVE_NEW_BAD_HABIT = 'SAVE_NEW_BAD_HABIT';
export const COMPLETE_DAILY_GOOD_HABIT = 'COMPLETE_DAILY_GOOD_HABIT';
export const COMPLETE_DAILY_BAD_HABIT = 'COMPLETE_DAILY_BAD_HABIT';
export const DECAY_HABITPOINTS_ON_START = 'DECAY_HABITPOINTS_ON_START';
export const RESET_WEEKLY_COUNTER = 'RESET_WEEKLY_COUNTER';
export const DELETE_GOOD_HABIT = 'DELETE_GOOD_HABIT';
export const DELETE_BAD_HABIT = 'DELETE_BAD_HABIT';
export const LEVEL_UP_GOOD_HABIT = 'LEVEL_UP_GOOD_HABIT';
export const LEVEL_UP_BAD_HABIT = 'LEVEL_UP_BAD_HABIT';
